In [68]:
import pandas as pd
import numpy as np

In [69]:
countries = pd.read_csv('country_centroids_az8.csv')
countries.head(n=5)

,FID,the_geom,FID_,scalerank,featurecla,labelrank,sovereignt,sov_a3,adm0_dif,level,...,region_un,subregion,region_wb,name_len,long_len,abbrev_len,tiny,homepart,Longitude,Latitude
0,country_centroids_az8.1,POINT (-69.9826771125 12.5208803838),0,3,Admin-0 country,5,Netherlands,NL1,1,2,...,Americas,Caribbean,Latin America & Caribbean,5,5,5,4,-99,-69.982677,12.520880
1,country_centroids_az8.2,POINT (66.0047336558 33.8352307278),1,1,Admin-0 country,3,Afghanistan,AFG,0,2,...,Asia,Southern Asia,South Asia,11,11,4,-99,1,66.004734,33.835231
2,country_centroids_az8.3,POINT (17.5373676815 -12.2933605438),2,1,Admin-0 country,3,Angola,AGO,0,2,...,Africa,Middle Africa,Sub-Saharan Africa,6,6,4,-99,1,17.537368,-12.293361
3,country_centroids_az8.4,POINT (-63.0649892654 18.2239595023),3,1,Admin-0 country,6,United Kingdom,GB1,1,2,...,Americas,Caribbean,Latin America & Caribbean,8,8,4,-99,-99,-63.064989,18.223959
4,country_centroids_az8.5,POINT (20.0498339611 41.1424498947),4,1,Admin-0 country,6,Albania,ALB,0,2,...,Europe,Southern Europe,Europe & Central Asia,7,7,4,-99,1,20.049834,41.142450

In [70]:
columns = countries.columns
columns

Index(['FID', 'the_geom', 'FID_', 'scalerank', 'featurecla', 'labelrank',
       'sovereignt', 'sov_a3', 'adm0_dif', 'level', 'type', 'admin', 'adm0_a3',
       'geou_dif', 'geounit', 'gu_a3', 'su_dif', 'subunit', 'su_a3',
       'brk_diff', 'name', 'name_long', 'brk_a3', 'brk_name', 'brk_group',
       'abbrev', 'postal', 'formal_en', 'formal_fr', 'note_adm0', 'note_brk',
       'name_sort', 'name_alt', 'mapcolor7', 'mapcolor8', 'mapcolor9',
       'mapcolor13', 'pop_est', 'gdp_md_est', 'pop_year', 'lastcensus',
       'gdp_year', 'economy', 'income_grp', 'wikipedia', 'fips_10', 'iso_a2',
       'iso_a3', 'iso_n3', 'un_a3', 'wb_a2', 'wb_a3', 'woe_id', 'adm0_a3_is',
       'adm0_a3_us', 'adm0_a3_un', 'adm0_a3_wb', 'continent', 'region_un',
       'subregion', 'region_wb', 'name_len', 'long_len', 'abbrev_len', 'tiny',
       'homepart', 'Longitude', 'Latitude'],
      dtype='object')

In [71]:
countries = countries.drop(['FID', 'the_geom', 'FID_', 'scalerank', 'featurecla', 'labelrank',
       'adm0_dif', 'level', 'type', 'admin', 'adm0_a3',
       'geou_dif', 'geounit', 'gu_a3', 'su_dif', 'subunit', 'su_a3',
       'brk_diff', 'name', 'name_long', 'brk_a3', 'brk_name', 'brk_group',
       'abbrev', 'postal', 'formal_en', 'formal_fr', 'note_adm0', 'note_brk',
       'name_sort', 'name_alt', 'mapcolor7', 'mapcolor8', 'mapcolor9',
       'mapcolor13', 'pop_est', 'gdp_md_est', 'pop_year', 'lastcensus',
       'gdp_year', 'economy', 'income_grp', 'wikipedia', 'fips_10', 'iso_a2',
       'iso_a3', 'iso_n3', 'un_a3', 'wb_a2', 'wb_a3', 'woe_id', 'adm0_a3_is',
       'adm0_a3_us', 'adm0_a3_un', 'adm0_a3_wb', 'continent', 'name_len', 'long_len', 'abbrev_len', 'tiny',
       'homepart'], axis=1)
countries.head(n=1)

,sovereignt,sov_a3,region_un,subregion,region_wb,Longitude,Latitude
0,Netherlands,NL1,Americas,Caribbean,Latin America & Caribbean,-69.982677,12.52088

In [72]:
countries = countries.sort_values(by='sovereignt')
countries.head(n=5)

,sovereignt,sov_a3,region_un,subregion,region_wb,Longitude,Latitude
1,Afghanistan,AFG,Asia,Southern Asia,South Asia,66.004734,33.835231
4,Albania,ALB,Europe,Southern Europe,Europe & Central Asia,20.049834,41.142450
62,Algeria,DZA,Africa,Northern Africa,Middle East & North Africa,2.617323,28.158938
6,Andorra,AND,Europe,Southern Europe,Europe & Central Asia,1.560544,42.542291
2,Angola,AGO,Africa,Middle Africa,Sub-Saharan Africa,17.537368,-12.293361

In [73]:
columns_titles = ["sovereignt","sov_a3","Latitude","Longitude","region_un","subregion","region_wb"]
countries = countries.reindex(columns=columns_titles)
countries.head(n=1)
countries

,sovereignt,sov_a3,Latitude,Longitude,region_un,subregion,region_wb
1,Afghanistan,AFG,33.835231,66.004734,Asia,Southern Asia,South Asia
4,Albania,ALB,41.142450,20.049834,Europe,Southern Europe,Europe & Central Asia
62,Algeria,DZA,28.158938,2.617323,Africa,Northern Africa,Middle East & North Africa
6,Andorra,AND,42.542291,1.560544,Europe,Southern Europe,Europe & Central Asia
2,Angola,AGO,-12.293361,17.537368,Africa,Middle Africa,Sub-Saharan Africa
...,...,...,...,...,...,...,...
233,Vietnam,VNM,16.646017,106.299147,Asia,South-Eastern Asia,East Asia & Pacific
185,Western Sahara,SAH,24.229567,-12.219828,Africa,Northern Africa,Middle East & North Africa
237,Yemen,YEM,15.909280,47.586762,Asia,Western Asia,Middle East & North Africa
239,Zambia,ZMB,-13.458242,27.774759,Africa,Eastern Africa,Sub-Saharan Africa
240,Zimbabwe,ZWE,-19.004204,29.851441,Africa,Eastern Africa,Sub-Saharan Africa

In [74]:
duplicated_countries = countries[countries.duplicated('sovereignt', keep=False)].sort_values('sovereignt')
countries = countries.drop([99,91,157,15,90,132,73,86,69,28,199,133,155,235,13,180,105,52,0,207,160,46,169,150,100,97,78,71,53,192,31,210,191,231,3,108,10,88,147,232,175])

In [75]:
countries.to_csv('countries.csv')